name: Build pull request
on:
    pull_request:

jobs:
    zola-check:
        name: check zola links & build
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - name: Install Zola
          run: |
            wget -O zola.deb https://github.com/barnumbirr/zola-debian/releases/download/v0.17.2-1/zola_0.17.2-1_amd64_bullseye.deb
            sudo dpkg -i zola.deb
        - name: Check Zola links
          run: |
            zola check
        - name: Check Zola build
          run: |
            zola build
